# Required
version: 2

formats:
  - epub
  - pdf

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  - install:
    - requirements: docs/requirements.txt